
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x800")
window.configure(bg = "#F1F1F1")


canvas = Canvas(
    window,
    bg = "#F1F1F1",
    height = 800,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    687.3258056640625,
    463.14605712890625,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=342.0,
    y=649.0,
    width=163.0,
    height=29.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=513.0,
    y=649.0,
    width=163.0,
    height=29.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=342.0,
    y=692.0,
    width=163.0,
    height=29.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=513.0,
    y=692.0,
    width=163.0,
    height=29.0
)

canvas.create_rectangle(
    0.0,
    8.089874267578125,
    221.12359619140625,
    815.7303161621094,
    fill="#80B3A7",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    122.2696533203125,
    53.707855224609375,
    image=image_image_2
)

canvas.create_text(
    17.528076171875,
    153.7078857421875,
    anchor="nw",
    text="Tipo de material",
    fill="#FFFFFF",
    font=("Inter Bold", 23 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=18.87640380859375,
    y=214.0,
    width=193.41290283203125,
    height=29.313589096069336
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=18.87640380859375,
    y=261.572998046875,
    width=193.41290283203125,
    height=29.427001953125
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    879.5723419189453,
    365.34625816345215,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=732.5716333389282,
    y=348.27252197265625,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    730.7864990234375,
    330.3370361328125,
    anchor="nw",
    text="URI da foto do material",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    879.5723419189453,
    304.6721248626709,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=732.5716333389282,
    y=287.598388671875,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    730.7864990234375,
    269.6629638671875,
    anchor="nw",
    text="Localização Física",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    512.8307647705078,
    602.6496639251709,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=365.8300561904907,
    y=585.575927734375,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    364.044921875,
    567.6404418945312,
    anchor="nw",
    text="Estado de conservação",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    514.1790924072266,
    547.3687191009521,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=367.1783838272095,
    y=530.2949829101562,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    365.39324951171875,
    512.3595581054688,
    anchor="nw",
    text="Data de aquisição",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    512.8307647705078,
    485.34625816345215,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=365.8300561904907,
    y=468.27252197265625,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    365.39324951171875,
    450.3370361328125,
    anchor="nw",
    text="Categoria",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    512.8307647705078,
    427.2816219329834,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=365.8300561904907,
    y=410.2078857421875,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    365.39324951171875,
    391.01123046875,
    anchor="nw",
    text="Número de série",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    512.8307647705078,
    367.6355037689209,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=365.8300561904907,
    y=350.561767578125,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    365.39324951171875,
    331.6854248046875,
    anchor="nw",
    text="Descrição",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    512.8307647705078,
    304.5849666595459,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=365.8300561904907,
    y=287.51123046875,
    width=294.0014171600342,
    height=32.1474723815918
)

canvas.create_text(
    365.39324951171875,
    269.6629638671875,
    anchor="nw",
    text="ID do item",
    fill="#344054",
    font=("Inter Bold", 11 * -1)
)

canvas.create_text(
    360.0,
    230.561767578125,
    anchor="nw",
    text="Digite todos os campos.",
    fill="#667085",
    font=("Inter", 13 * -1)
)

canvas.create_text(
    307.415771484375,
    186.0673828125,
    anchor="nw",
    text="Materiais Didáticos",
    fill="#344054",
    font=("Inter Bold", 26 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    884.8988647460938,
    563.561767578125,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    885.516845703125,
    534.3033447265625,
    image=image_image_4
)

canvas.create_text(
    853.483154296875,
    602.6966552734375,
    anchor="nw",
    text="ID do item",
    fill="#FFFFFF",
    font=("Inter Bold", 11 * -1)
)

canvas.create_text(
    360.0,
    116.97576904296875,
    anchor="nw",
    text="Cadastro de livros e materiais.",
    fill="#667085",
    font=("Inter", 13 * -1)
)

canvas.create_text(
    360.0,
    72.80899047851562,
    anchor="nw",
    text="Acervo",
    fill="#344054",
    font=("Inter Bold", 33 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=272.0,
    y=73.0,
    width=69.0,
    height=69.0
)
window.resizable(False, False)
window.mainloop()
