
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gabri\OneDrive - Universidade de Brasília\Área de Trabalho\Tkinter-Designer-master\Telas Geradas\build\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x800")
window.configure(bg = "#F1F1F1")


canvas = Canvas(
    window,
    bg = "#F1F1F1",
    height = 800,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    126.741455078125,
    128.08990478515625,
    496.50042724609375,
    659.3258666992188,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    287.550537109375,
    393.08990478515625,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    651.404541015625,
    214.08990478515625,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    988.16845703125,
    393.08990478515625,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=165.0,
    y=559.8654174804688,
    width=266.0,
    height=46.13458251953125
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=219.0,
    y=614.8612060546875,
    width=153.0,
    height=28.1387939453125
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=699.76220703125,
    y=259.0,
    width=78.23779296875,
    height=25.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    618.8763809204102,
    268.9887638092041,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=556.209792137146,
    y=258.87640380859375,
    width=125.33317756652832,
    height=18.224720001220703
)

canvas.create_text(
    552.390625,
    244.61614990234375,
    anchor="nw",
    text="Selecione uma foto de perfil",
    fill="#344054",
    font=("Inter Medium", 13 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    641.51513671875,
    188.08294677734375,
    image=image_image_4
)

canvas.create_text(
    173.54638671875,
    185.4259033203125,
    anchor="nw",
    text="Edite o seu perfil.",
    fill="#667085",
    font=("Inter", 11 * -1)
)

canvas.create_text(
    173.54638671875,
    147.98199462890625,
    anchor="nw",
    text="Perfil",
    fill="#344054",
    font=("Inter Bold", 28 * -1)
)

canvas.create_text(
    845.3931884765625,
    152.35955810546875,
    anchor="nw",
    text="Histórico",
    fill="#344054",
    font=("Inter Bold", 33 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    297.98834228515625,
    520.0404415130615,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=170.41503286361694,
    y=505.22314453125,
    width=255.1466188430786,
    height=27.634593963623047
)

canvas.create_text(
    168.86572265625,
    489.657958984375,
    anchor="nw",
    text="Função",
    fill="#344054",
    font=("Inter Medium", 10 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    296.81842041015625,
    466.2147579193115,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=169.24511098861694,
    y=451.3974609375,
    width=255.1466188430786,
    height=27.634593963623047
)

canvas.create_text(
    168.86572265625,
    435.83233642578125,
    anchor="nw",
    text="Senha",
    fill="#344054",
    font=("Inter Medium", 10 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    296.81842041015625,
    412.313512802124,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=169.24511098861694,
    y=397.4962158203125,
    width=255.1466188430786,
    height=27.634593963623047
)

canvas.create_text(
    168.86572265625,
    382.006591796875,
    anchor="nw",
    text="Email",
    fill="#344054",
    font=("Inter Medium", 10 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    296.81842041015625,
    359.6578731536865,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=169.24511098861694,
    y=344.840576171875,
    width=255.1466188430786,
    height=27.634593963623047
)

canvas.create_text(
    168.86572265625,
    328.18096923828125,
    anchor="nw",
    text="Nome de usuário",
    fill="#344054",
    font=("Inter Medium", 10 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    296.81842041015625,
    307.8946285247803,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=169.24511098861694,
    y=293.07733154296875,
    width=255.1466188430786,
    height=27.634593963623047
)

canvas.create_text(
    168.86572265625,
    276.695556640625,
    anchor="nw",
    text="Último sobrenome",
    fill="#344054",
    font=("Inter Medium", 10 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    296.81842041015625,
    253.17667198181152,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=169.24511098861694,
    y=238.359375,
    width=255.1466188430786,
    height=27.634593963623047
)

canvas.create_text(
    168.86572265625,
    222.869873046875,
    anchor="nw",
    text="Primeiro nome",
    fill="#344054",
    font=("Inter Medium", 10 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    155.9775390625,
    63.146087646484375,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    986.3931884765625,
    425.382080078125,
    image=image_image_6
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=93.0,
    y=145.0,
    width=69.0,
    height=69.0
)
window.resizable(False, False)
window.mainloop()
