
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gabri\OneDrive - Universidade de Brasília\Área de Trabalho\Tkinter-Designer-master\Telas Geradas\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x800")
window.configure(bg = "#F1F1F1")


canvas = Canvas(
    window,
    bg = "#F1F1F1",
    height = 800,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    710.955078125,
    655.6854248046875,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    520.955078125,
    350.10107421875,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    110.0,
    411.08984375,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    122.2696533203125,
    53.7078857421875,
    image=image_image_4
)

canvas.create_text(
    17.528076171875,
    153.7078857421875,
    anchor="nw",
    text="Tipo de material",
    fill="#FFFFFF",
    font=("Inter Bold", 23 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=19.0,
    y=214.0,
    width=194.0,
    height=29.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=19.0,
    y=262.0,
    width=194.0,
    height=29.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=559.5505981445312,
    y=405.84271240234375,
    width=71.44940185546875,
    height=31.15728759765625
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=11.0,
    y=507.0,
    width=201.0,
    height=35.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=11.0,
    y=554.0,
    width=201.0,
    height=35.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=397.7528076171875,
    y=499.0,
    width=73.24717712402344,
    height=23.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    467.1910095214844,
    419.3258590698242,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=402.31478786468506,
    y=405.84271240234375,
    width=129.75244331359863,
    height=24.966293334960938
)

canvas.create_text(
    401.9730224609375,
    392.35955810546875,
    anchor="nw",
    text="ISBN",
    fill="#344054",
    font=("Inter Bold", 9 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    466.7528076171875,
    463.33709716796875,
    image=image_image_5
)

canvas.create_text(
    401.9730224609375,
    436.85394287109375,
    anchor="nw",
    text="Quantidade de exemplares",
    fill="#344054",
    font=("Inter Bold", 9 * -1)
)

canvas.create_text(
    431.460693359375,
    183.370849609375,
    anchor="nw",
    text="Acervo De Livros",
    fill="#344054",
    font=("Inter Bold", 21 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    520.8202514648438,
    304.3033447265625,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    520.6067504882812,
    295.0189208984375,
    image=image_image_7
)

canvas.create_text(
    496.1798095703125,
    349.138427734375,
    anchor="nw",
    text="Título Livro",
    fill="#FFFFFF",
    font=("Inter Bold", 9 * -1)
)

canvas.create_text(
    355.955078125,
    110.2342529296875,
    anchor="nw",
    text="Realiza o empréstimo e devoluções de livros e materiais.",
    fill="#667085",
    font=("Inter", 13 * -1)
)

canvas.create_text(
    355.955078125,
    66.0673828125,
    anchor="nw",
    text="Empréstimo",
    fill="#344054",
    font=("Inter Bold", 33 * -1)
)

canvas.create_text(
    355.955078125,
    66.0673828125,
    anchor="nw",
    text="Empréstimos E Devoluções",
    fill="#344054",
    font=("Inter Bold", 33 * -1)
)

canvas.create_text(
    378.87640380859375,
    595.955078125,
    anchor="nw",
    text="O que deseja fazer?",
    fill="#344054",
    font=("Inter Bold", 33 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    899.483154296875,
    351.10107421875,
    image=image_image_8
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=779.0,
    y=498.0,
    width=73.24717712402344,
    height=23.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=924.94384765625,
    y=405.0,
    width=77.05615234375,
    height=31.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=375.0,
    y=666.0,
    width=243.0,
    height=43.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=664.0,
    y=664.0,
    width=243.0,
    height=43.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    842.0225830078125,
    419.3258590698242,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=779.8429861068726,
    y=405.84271240234375,
    width=124.35919380187988,
    height=24.966293334960938
)

canvas.create_text(
    779.6639404296875,
    392.35955810546875,
    anchor="nw",
    text="ID do Usuário",
    fill="#344054",
    font=("Inter Bold", 9 * -1)
)

canvas.create_text(
    857.528076171875,
    183.370849609375,
    anchor="nw",
    text="Usuário",
    fill="#344054",
    font=("Inter Bold", 21 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    898.5111083984375,
    304.3033447265625,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    898.297607421875,
    295.0189208984375,
    image=image_image_10
)

canvas.create_text(
    886.0054931640625,
    349.138427734375,
    anchor="nw",
    text="Nome",
    fill="#FFFFFF",
    font=("Inter Bold", 9 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    769.6629638671875,
    188.539306640625,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    388.08990478515625,
    188.539306640625,
    image=image_image_12
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=267.0,
    y=66.0,
    width=69.0,
    height=69.0
)

canvas.create_text(
    408.0,
    457.0,
    anchor="nw",
    text="1",
    fill="#000000",
    font=("Inter Medium", 10 * -1)
)
window.resizable(False, False)
window.mainloop()
