
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gabri\OneDrive - Universidade de Brasília\Área de Trabalho\Tkinter-Designer-master\Telas Geradas\build\assets\frame6")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x800")
window.configure(bg = "#F1F1F1")


canvas = Canvas(
    window,
    bg = "#F1F1F1",
    height = 800,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    66.0673828125,
    741.5730590820312,
    anchor="nw",
    text="Grupo 5 - UnB 2023/2 - BDT02",
    fill="#667085",
    font=("Inter Regular", 13 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    266.9326171875,
    412.05615234375,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    845.0,
    414.1666259765625,
    image=image_image_2
)

canvas.create_text(
    112.228515625,
    580.046875,
    anchor="nw",
    text="Não tem uma conta? Cadastre-se",
    fill="#344054",
    font=("Inter", 11 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=112.0,
    y=515.880126953125,
    width=310.0,
    height=53.119873046875
)

canvas.create_text(
    114.728515625,
    483.38018798828125,
    anchor="nw",
    text="Esqueceu a senha?",
    fill="#2F7967",
    font=("Inter Medium", 11 * -1)
)

canvas.create_text(
    110.561767578125,
    273.380126953125,
    anchor="nw",
    text="Por favor, digite as suas informações para logar.",
    fill="#667085",
    font=("Inter", 13 * -1)
)

canvas.create_text(
    110.561767578125,
    229.2135009765625,
    anchor="nw",
    text="Login",
    fill="#344054",
    font=("Inter Bold", 33 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    263.4784393310547,
    447.1302089691162,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=116.39510154724121,
    y=430.046875,
    width=294.16667556762695,
    height=32.16666793823242
)

canvas.create_text(
    114.728515625,
    406.71356201171875,
    anchor="nw",
    text="Senha",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    263.4784393310547,
    368.79677391052246,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=116.39510154724121,
    y=351.71343994140625,
    width=294.16667556762695,
    height=32.16666793823242
)

canvas.create_text(
    114.728515625,
    334.2135009765625,
    anchor="nw",
    text="Ex.: 19xxxx111@aluno.unb.br",
    fill="#667085",
    font=("Inter", 9 * -1)
)

canvas.create_text(
    114.728515625,
    321.71337890625,
    anchor="nw",
    text="Email",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    155.9775390625,
    63.1461181640625,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
