<<<<<<< HEAD

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gabri\OneDrive - Universidade de Brasília\Área de Trabalho\Tkinter-Designer-master\Telas Geradas\build\assets\frame5")

=======
import tkinter as tk
from tkinter import *
from tkinter import messagebox
from tkinter import ttk


def verificar_cadastro():
    if entrada_nome.get() == "" or entrada_senha == "" or entrada_sobrenome == "" or entrada_usuario == "":
        messagebox.showerror("Erro", "Falha ao criar conta!")
    else:
        messagebox.showinfo("Sucesso!", "Cadastro Concluido!")

#cores--------------------------------------------------------------------------------------------
cor1 = "#ffffff"  # branca

#janela------------------------------------------------------------------------------------------
janela_cadastro = tk.Tk()
janela_cadastro.title("Cadastro")
janela_cadastro.geometry("800x600")
janela_cadastro.configure(background=cor1)
janela_cadastro.resizable(width=False, height=False)

#Dividindo a janela------------------------------------------------------------------------------------------
barra_titulo = Frame(janela_cadastro, width=800, height=200, relief="flat")
barra_titulo.grid(row=1, column=0, pady=0, padx=0, sticky=NSEW)

barra_dados = Frame(janela_cadastro, width=800, height=200, relief="flat")
barra_dados.grid(row=2, column=0, pady=0, padx=0, sticky=NSEW)

barra_interacoes = Frame(janela_cadastro, width=800, height=200, relief="flat")
barra_interacoes.grid(row=3, column=0, pady=0, padx=0, sticky=NSEW)


tk.Label(barra_titulo, text="Cadastro", font=("Verdana", 30, "bold")).grid(padx=300)

label_usuario = tk.Label(barra_dados, text="Usuario:", font=("Verdana", 12, "bold"))
label_usuario.grid(row=2)
label_nome = tk.Label(barra_dados, text="Nome:", font=("Verdana", 12, "bold"))
label_nome.grid(row=3)
label_sobrenome = tk.Label(barra_dados, text="Sobrenome:",font=("Verdana", 12, "bold"))
label_sobrenome.grid(row=4)
label_senha = tk.Label(barra_dados, text="Senha:",font=("Verdana", 12, "bold"))
label_senha.grid(row=5)
label_funcao = tk.Label(barra_dados, text="Funcao:", font=("Verdana", 12, "bold"))


entrada_usuario = tk.Entry(barra_dados, width=50)
entrada_senha = tk.Entry(barra_dados, width= 50, show="*")
entrada_nome = tk.Entry(barra_dados, width= 50)
entrada_sobrenome = tk.Entry(barra_dados, width= 50)
entrada_usuario.grid(row=2, column=1)
entrada_nome.grid(row=3, column=1)
entrada_sobrenome.grid(row=4, column=1)
entrada_senha.grid(row=5, column=1)

tk.Label(barra_interacoes, text="Tipo de cadastro:", font=("Verdana", 12, "bold")).grid(row=6, column=0)
n = tk.StringVar()
tipo_combo_box = ttk.Combobox(barra_interacoes, width= 15, textvariable=n, font=("Verdana", 12, "bold"))
tipo_combo_box["values"] = ("Cliente", "Administrador")
tipo_combo_box.grid(row= 6, column=1)

botao_concluir = tk.Button(barra_interacoes, text="Cadastrar",font=("Verdana", 12, "bold"), command=verificar_cadastro)
botao_concluir.grid()
botao_voltar = tk.Button(barra_interacoes, text="Voltar",font=("Verdana", 12, "bold"), command=janela_cadastro.destroy)
botao_voltar.grid()
>>>>>>> ae4bd00565f3339b684a122400c4131ff41a1cb3

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x800")
window.configure(bg = "#F1F1F1")


canvas = Canvas(
    window,
    bg = "#F1F1F1",
    height = 800,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    271.010009765625,
    435.5109558105469,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    871.347412109375,
    276.30352783203125,
    image=image_image_2
)

canvas.create_text(
    110.6240234375,
    690.1362915039062,
    anchor="nw",
    text="Já tem uma conta? Faça login",
    fill="#344054",
    font=("Inter", 11 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=109.0,
    y=625.9696655273438,
    width=312.0,
    height=56.03033447265625
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=947.0,
    y=337.0,
    width=92.0,
    height=30.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    266.2386932373047,
    588.1485805511475,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=119.1553544998169,
    y=571.0652465820312,
    width=294.1666774749756,
    height=32.16666793823242
)

canvas.create_text(
    117.369384765625,
    553.1197509765625,
    anchor="nw",
    text="Função",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    264.8895721435547,
    526.0912075042725,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=117.8062334060669,
    y=509.00787353515625,
    width=294.1666774749756,
    height=32.16666793823242
)

canvas.create_text(
    117.369384765625,
    491.0624084472656,
    anchor="nw",
    text="Senha",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    264.8895721435547,
    463.9467372894287,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=117.8062334060669,
    y=446.8634033203125,
    width=294.1666774749756,
    height=32.16666793823242
)

canvas.create_text(
    117.369384765625,
    429.00506591796875,
    anchor="nw",
    text="Email",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    264.8895721435547,
    403.2384548187256,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=117.8062334060669,
    y=386.1551208496094,
    width=294.1666774749756,
    height=32.16666793823242
)

canvas.create_text(
    117.369384765625,
    366.9477233886719,
    anchor="nw",
    text="Nome de usuário",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    264.8895721435547,
    343.5588893890381,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=117.8062334060669,
    y=326.4755554199219,
    width=294.1666774749756,
    height=32.16666793823242
)

canvas.create_text(
    117.369384765625,
    307.5885314941406,
    anchor="nw",
    text="Último sobrenome",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    264.8895721435547,
    280.4728603363037,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=117.8062334060669,
    y=263.3895263671875,
    width=294.1666774749756,
    height=32.16666793823242
)

canvas.create_text(
    117.369384765625,
    245.5312042236328,
    anchor="nw",
    text="Primeiro nome",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    826.3069076538086,
    349.70201778411865,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=719.254141330719,
    y=337.26812744140625,
    width=214.1055326461792,
    height=22.867780685424805
)

canvas.create_text(
    715.0084228515625,
    314.3338928222656,
    anchor="nw",
    text="Selecione uma foto de perfil",
    fill="#344054",
    font=("Inter Medium", 11 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    856.2073974609375,
    226.1905517578125,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    868.0,
    576.0,
    image=image_image_4
)

canvas.create_text(
    111.972900390625,
    202.0081329345703,
    anchor="nw",
    text="Por favor, digite as suas informações para o cadastro.",
    fill="#667085",
    font=("Inter", 13 * -1)
)

canvas.create_text(
    111.972900390625,
    157.84149169921875,
    anchor="nw",
    text="Cadastro",
    fill="#344054",
    font=("Inter Bold", 33 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    172.198974609375,
    60.47216796875,
    image=image_image_5
)
window.resizable(False, False)
window.mainloop()
